spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: 1234
    url: jdbc:mariadb://localhost:3306/nodamen?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    hikari:
      maximum-pool-size: 12

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hiberate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true

server:
  port: 8080
