jwt:
  header: Authorization
  secret: $2a$12$kZFc6e2lo/x8/HegxuBNyeI6hsSXWXytYd.hCvlmvbqdoX5PnCL22
  expiration: 604800
server:
  port: 8081

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/template/
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: nodamen
    url: jdbc:mariadb://localhost:3306/adminpage?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
  web:
    resources:
      add-mappings: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hiberate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect